name: Test R-universe

on:
  pull_request:
    branches: [main, master]
    paths:
      - 'R/**'
      - 'src/**'
      - 'tests/**'
      - 'data/**'
      - 'inst/**'
      - 'DESCRIPTION'
      - 'NAMESPACE'
  workflow_dispatch:

jobs:
  build:
    name: R-universe testing
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: ${{ github.repository_owner }}
